version: "3.8"

services:
  app:
    container_name: gateway-frontend-dev
    image: gateway-frontend-dev
    build:
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
